spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/store?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: shc1034813562
  jackson:
    default-property-inclusion: non_null

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.shen.experiment_store.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

user:
  address:
    max-count: 20
